### ISSUE TITLE
Shelly Wave (Zwave new product lineup)

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/firmware-updates#106] opened 2024-01-19 11:43 UTC
Hi,

I'm not an expert of this repo, so i'm not really sure how to add these firmwares to the database.

But Shelly has made their firmwares publicly available for their 4 new Zwave modules

https://support.shelly.cloud/en/support/solutions/articles/103000258471-firmware-updates

Could some integrate them to this repo ? Or tell me how to do so ? Thanks in advance :)

**Comment by AlCalzone** [comment] 2024-02-02 08:44
Duplicate of #95

**Closed by AlCalzone** 2024-02-02 08:44 UTC
